settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: app
    path: .
    commands:
      install:
        status: true
        method: go build -o helloworld
      run:
        status: true
        method: ./helloworld
    watcher:
      extensions:
        - go
      paths:
        - /
      ignore:
        paths:
          - .git
          - .realize
          - vendor
